### ISSUE TITLE
I can not find 'signnames.csv'.

### ISSUE THREAD

**Issue by sounansu** [georgesung/ssd_tensorflow_traffic_sign_detection#1]
First, I try to run inference.py
-----
$ python inference.py -m demo
.
.
Traceback (most recent call last):
  File "inference.py", line 271, in <module>
    generate_output(input_files, mode)
  File "inference.py", line 188, in generate_output
    with open('signnames.csv', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'signnames.csv'
------------------------------
I can not find 'signnames.csv' in your git.

Is that in 'LISA Traffic Sign Dataset' ?

**Comment by sounansu** [comment]
I download 'LISA Traffic Sign Dataset'.
But I can not find signnames.csv in that.

**Comment by georgesung** [comment]
Thanks for the catch, I forgot to include signnames.csv in this repo. I have just added it. It is basically a hand-generated file (or can be generated with simple script) that maps sign integer ID to sign name string, but reserving ID 0 for background (no need to explicitly map 0->background though). Let me know if inference.py works now. Thanks.

**Comment by sounansu** [comment]
Thanks, you added signnames.csv file.
I can run "inference.py -m demo". It is very nice!.
But my GPU card is poor, so tensorflow says 'Ran out of memory trying to allocate 2.14GiB.'.

ssd-caffe (by Weiliu) could not train on my system. ( Out of memory?).
mxnet-ssd( by Zhreshold) could but training time is very huge on my system ( Poor GPU?).
ssd_keras(by rykov8) could not train for lost training data set(framexxx.png).

After I will try training to use your system.

Thank you for sharing your software!

**Comment by georgesung** [comment]
Cool, sounds good! I haven't documented the data pre-processing steps, so you might have to look through the code to figure it out :S But my base network is AlexNet so training should not take so much resources compared to the original VGG16 base network. Also if you run out of memory a work-around is to reduce your batch size.

**Comment by sounansu** [comment]
Very very thanks!
I try to run inference.py not only png files but also mp4 moview files.
It works fine!

So, now I tried to run data_prep.py for training.
I think it make pickle data for train.py

But, this python program need pickle data too. It it true?

```python:data_prep.py
if __name__ == '__main__':
        with open('data_raw_%sx%s.p' % (IMG_W, IMG_H), 'rb') as f:
                data_raw = pickle.load(f)

        print('Preparing data (i.e. matching boxes)')
        data_prep = do_data_prep(data_raw)

        with open('data_prep_%sx%s.p' % (IMG_W, IMG_H), 'wb') as f:
                pickle.dump(data_prep, f)

        print('Done. Saved prepared data to data_prep_%sx%s.p' % (IMG_W, IMG_H))
        print('Total images with >=1 matching box: %d' % len(data_prep.keys()))
```

I think this code need data_raw_400x260.p file.

(....I wonder it was generated by AlexNet traing time?)

**Comment by georgesung** [comment]
Yup, I haven't documented that part in detail, I'll work on the documentation this weekend~

**Comment by sounansu** [comment]
Oh!. don't worry!
My ubuntu PC 's tensorflow environment is broken and needs to be repaired.

So, if only inference can be on my windows PC.

And, thank you for your quick response!

**Comment by georgesung** [comment]
I added some instructions to the README, about how to train from scratch. Let me know if that helps!

**Comment by sounansu** [comment]
Thank you.
But, my tensorflow environment is not good....
And Google Release tensorflow version 1.0.

Your inference.py is not work under my environment now.(Last week, it worked last week..)
So, I revise the environment of tensorflow to 0.12 and try your training python script.

Regards,
