### ISSUE TITLE
How to fix this problem?

### ISSUE THREAD

**Issue by babymilo** [georgesung/ssd_tensorflow_traffic_sign_detection#15]
When i running this command "python inference.py -m demo"

Restoring previously trained model at ./model.ckpt
Demo mode: Running inference on images in sample_images/
Running inference on sample_images/.DS_Store
Traceback (most recent call last):
  File "inference.py", line 189, in <module>
    generate_output(input_files, mode)
  File "inference.py", line 158, in generate_output
    image_orig = np.asarray(Image.open('sample_images/' + image_file))
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 2519, in open
    % (filename if filename else fp))
IOError: cannot identify image file 'sample_images/.DS_Store'

**Comment by georgesung** [comment]
The simple work-around is to remove the directory ".DS_Store". If the .DS_Store directory gets automatically created (e.g. on a Mac), you can try updating the inference.py script to ignore ".DS_Store".
