### ISSUE TITLE
 runing inference.py is error.No module named 'sklearn.model_selection'.I find sklearn,but no 'sklearn.model_selection

### ISSUE THREAD

**Issue by RoseLii** [georgesung/ssd_tensorflow_traffic_sign_detection#16]
please help me 

/ssd$ python inference.py
Traceback (most recent call last):
  File "inference.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ImportError: No module named 'sklearn.model_selection'
why has a error?

**Comment by RoseLii** [comment]
I find sklearn ,but no sklearn.model_selection

**Comment by georgesung** [comment]
You might have a different version of sklearn than me. Try to import train_test_split from cross_validation instead:

from sklearn.cross_validation import train_test_split
