### ISSUE TITLE
I am runing  inference.py,but it have a problom  input_files = glob.glob(input_dir + '/*.*'),unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by RoseLii** [georgesung/ssd_tensorflow_traffic_sign_detection#17]
please help me

Traceback (most recent call last):
  File "D:/traffic_sign/ssd/ssd/inference.py", line 185, in <module>
    input_files = glob.glob(input_dir + '/*.*')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
I think the error that is input_dir,but
	parser = OptionParser()
	parser.add_option('-i', '--input_dir', dest='input_dir',type='string',
		help='Directory of input videos/images (ignored for "demo" mode). Will run inference on all videos/images in that dir')
	parser.add_option('-m', '--mode', dest='mode', default='image',
		help='Operating mode, could be "image", "video", or "demo"; "demo" mode displays annotated images from sample_images/')
	# Get and parse command line options
	options, args = parser.parse_args(args)
        put_dir = options.input_dir

what are --input_dir  input file?the help prompt should not be the path(image or video),but it's wrong for me to enter the path of sample_images.
Please help me if I am wrong.

**Comment by georgesung** [comment]
What are the arguments you passed to inference.py? Can you share the complete command you used to run inference.py?
