### ISSUE TITLE
Error when I run python inference.py -m demo

### ISSUE THREAD

**Issue by lizhaoda** [georgesung/ssd_tensorflow_traffic_sign_detection#2]
First, I git clone https://github.com/georgesung/ssd_tensorflow_traffic_sign_detection.git
Then,I cd ssd_tensorflow_traffic_sign_detection.
And I run python inference.py -m demo, but error:

I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "inference.py", line 6, in <module>
    from model import SSDModel
  File "/home/ubuntu/ssd_tensorflow_traffic_sign_detection/model.py", line 241
    box = (*box_coords, cls, cls_prob)
           ^
SyntaxError: invalid syntax

**Comment by georgesung** [comment]
Which version of python do you have?

**Comment by lizhaoda** [comment]
@georgesung  python 2.7.12 .I see your version of python is 3.5, and could you give me some advise about how to run on 2.7.12?

**Comment by georgesung** [comment]
It is up to you whether you want to stick with Python 2.7 or migrate to Python 3.5, but if you want to stick with Python 2.7, you can reference something like http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html to see how to modify my code.
