### ISSUE TITLE
when i run interface.py , I got a problem as flow. i don't know why,hope for your help.

### ISSUE THREAD

**Issue by Suodislie** [georgesung/ssd_tensorflow_traffic_sign_detection#3]
**File "/home/hg/anaconda3b/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
_AssertCompatible(values, dtype)
File "/home/hg/anaconda3b/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
(dtype.name, repr(mismatch), type(mismatch).name))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.**

**Comment by chenweiqian** [comment]
I also have this problem.

**Comment by chenweiqian** [comment]
@Suodislie   It's problem about tensorflow version. you can do some change in model.py as below:
change
`	final_pred_conf = tf.concat(1,preds_conf)
	final_pred_loc = tf.concat(1,preds_loc )`

to
`	final_pred_conf = tf.concat(preds_conf,1)
	final_pred_loc = tf.concat(preds_loc,1 )`

**Comment by georgesung** [comment]
Thanks, I haven't tested this in the latest TensorFlow v1.x yet. The code was developed in TensorFlow v0.12, which is being phased out. Will update this for TF v1 soon!

**Comment by Suodislie** [comment]
@chenweiqian Ths for your help, I have solved this problem by changing version before see your help
