### ISSUE TITLE
Can't find mergedAnnotations.csv'

### ISSUE THREAD

**Issue by betsyweilin** [georgesung/ssd_tensorflow_traffic_sign_detection#6]
I use below command, and find no such file mergedAnnotations.csv, any suggestions?
I download LISA data ,but 
$ python create_pickle.py
Traceback (most recent call last):
  File "create_pickle.py", line 36, in <module>
    with open('mergedAnnotations.csv', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'mergedAnnotations.csv'

Thanks!

**Comment by georgesung** [comment]
Hello, please follow instructions in the LISA Traffic Sign Dataset to create 'mergedAnnotations.csv' such that only stop signs and pedestrian crossing signs are shown

**Comment by deeplearner12138** [comment]
怎么生成这个呢 代码感觉有错误
