### ISSUE TITLE
where is the mergedAnnotations.csv??

### ISSUE THREAD

**Issue by liuguiyangnwpu** [georgesung/ssd_tensorflow_traffic_sign_detection#9]
hi,
I want to train your net model, use your given datasets.
But I did not found the **mergedAnnotations.csv**.

```
# For speed, put entire contents of mergedAnnotations.csv in memory
merged_annotations = []
with open('mergedAnnotations.csv', 'r') as f:
	for line in f:
		line = line[:-1]  # strip trailing newline
		merged_annotations.append(line)
```

thx

**Comment by georgesung** [comment]
From README.md:

Training the model from scratch:

* Download the LISA Traffic Sign Dataset, and store it in a directory $LISA_DATA
* cd $LISA_DATA
* Follow instructions in the LISA Traffic Sign Dataset to create 'mergedAnnotations.csv' such that only stop signs and pedestrian crossing signs are shown
...

**Comment by sunlung** [comment]
Use signDatabasePublicFramesOnly\tools\mergeAnnotationFiles.py to create the csv

**Comment by sudonto** [comment]
@sunlung
how to filter only stop sign and pedestrian in mergeAnnotation.csv? really need your help.
thank you.
